---
# Minimal 2-node inventory for learning purposes
all:
  hosts:
    cp-01:
      ansible_host: 10.0.1.3
      ip: 10.0.1.3
      access_ip: 10.0.1.3
    worker-01:
      ansible_host: 10.0.1.4
      ip: 10.0.1.4
      access_ip: 10.0.1.4
  children:
    kube_control_plane:
      hosts:
        cp-01: {}
    etcd:
      hosts:
        cp-01: {}
    k8s_cluster:
      children:
        kube_control_plane: {}
        k8s_node:
          hosts:
            worker-01: {}
    k8s_node:
      hosts:
        worker-01: {}
    calico_rr:
      hosts: {}
